### ISSUE TITLE
where pathGenerate

### ISSUE THREAD

**Issue by pengchuan99** [caogang1213/gpmpc#1]
path = pathGenerate(0.5, 300, 'Elliptical')?

**Comment by caogang1213** [comment]
you can find it under <https://github.com/caogang1213/mytool.git>

**Comment by pengchuan99** [comment]
very appreciate

**Comment by pengchuan99** [comment]
i have read severy articles of your gpmpc and have a question.can i  use the gp to learn all quadrotor model instead of learn by One-dimensional use gp

**Comment by caogang1213** [comment]
Sorry I don't quite understand your question.

**Comment by pengchuan99** [comment]
oh,sorry i didn't  express  my question clearly,maybe  i need do more research then to ask question.appreciate again

**Comment by caogang1213** [comment]
No worries. Thanks for your interests. I am happy to discuss if you have any questions about GPMPC. Good luck. 

Gang Cao 
caogang1213@gmail.com

**Comment by pengchuan99** [comment]
ok thank a lot
